### ISSUE TITLE
Add an example on how to use

### ISSUE THREAD

**Issue by mojoaxel** [hpe-idol/sunburst#1]
Can you please add an simple example on how the `options` must be structured to show a simple sunburst chart:

```js
requirejs(["src/js/sunburst"], function(Sunburst) {
	var sunburst = new Sunburst('#sunburst', {
		data: {}
	});
});
```

I'm currently looking into different existing implementations and I'm curious about yours! Thanks!

**Comment by ghost** [comment]
Hi mojoaxel,

Thanks for pointing this out. I've now added a README with some documentation in it.

**Comment by mojoaxel** [comment]
Thx!
